sudo: false
language: node_js
node_js:
  - '5'
addons:
  firefox: '46.0'
install:
  - npm install
  - webdriver-manager update
before_script:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
script:
  - npm start &
  - sleep 10
  - webdriver-manager start &
  - sleep 10
  - npm test
